# Macro file for the initialization phase of example B5
# when running in interactive mode with visualization
#
# Set some default verbose
#
/control/verbose 0
/control/saveHistory
# verbosity: 2 is VERY chatty
/run/verbose 0 

# comment this when checking models
/process/had/verbose 0
/process/em/verbose 0

#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
